name: Angular Build and Deploy Workflow
on:
 push:
   branches: ["main"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test:prod

      - name: Build
        run: npm run build:prod

      - name: CNAME Update
        run: echo "mock.codewithram.dev" > dist/mock-exam-app/CNAME

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: docs
          build_dir: dist/mock-exam-app/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

