name: Angular Build and Deploy Workflow
on:
 push:
   branches: ["main"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        
      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test:prod

      - name: Build & Package
        run: npm run package:prod

      - name: Publish
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "deploy@nramc.noreply.github.com"
          git add .
          git commit -m "Release Preparation: Publish artifact to docs"
          git push
